# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby_gallery"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Dang"]
  s.date = "2013-03-22"
  s.description = "Upload image use gallery"
  s.email = "peter@rubify.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/ruby_gallery.js",
    "app/assets/stylesheets/ruby_gallery.css.scss",
    "app/controllers/attachments_controller.rb",
    "app/helpers/ruby_gallery/ruby_gallery_helper.rb",
    "app/helpers/ruby_gallery/test_helper.rb",
    "app/models/album_attachment.rb",
    "app/models/album_photo.rb",
    "lib/generators/active_record/ruby_gallery_generator.rb",
    "lib/generators/active_record/templates/album_attachment_migration.rb",
    "lib/generators/active_record/templates/album_photo_migration.rb",
    "lib/generators/active_record/templates/migration.rb",
    "lib/generators/ruby_gallery/install_generator.rb",
    "lib/generators/ruby_gallery/ruby_gallery_generator.rb",
    "lib/ruby_gallery.rb",
    "ruby_gallery.gemspec",
    "test/helper.rb",
    "test/test_ruby_gallery.rb"
  ]
  s.homepage = "http://github.com/dangluan/ruby_gallery"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Help to create gallery"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bourbon>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<compass-rails>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, ["~> 3.0"])
      s.add_runtime_dependency(%q<jquery-fileupload-rails>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.4"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<bourbon>, ["~> 3.0.0"])
      s.add_dependency(%q<compass-rails>, [">= 0"])
      s.add_dependency(%q<paperclip>, ["~> 3.0"])
      s.add_dependency(%q<jquery-fileupload-rails>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.3.4"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<bourbon>, ["~> 3.0.0"])
    s.add_dependency(%q<compass-rails>, [">= 0"])
    s.add_dependency(%q<paperclip>, ["~> 3.0"])
    s.add_dependency(%q<jquery-fileupload-rails>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.3.4"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

